const express = require("express");
const categoryController = require("../../controllers/admin-controllers/category");
const productController = require("../../controllers/admin-controllers/product");
const usercontroller = require("../../controllers/admin-controllers/user");
const orderController = require("../../controllers/admin-controllers/order");
const discountController = require("../../controllers/admin-controllers/discount");
const orderNController = require("../../controllers/admin-controllers/orderN");
const blogController = require("../../controllers/admin-controllers/blog");
const supplierController = require("../../controllers/admin-controllers/supplier");
const router = express.Router();

router.get("/supplier", supplierController.getAllSupplier);
router.get("/blogs", blogController.getAllBlog);
router.get("/category-and-supplier", categoryController.getCategoryAndSupplier);
router.get("/product", productController.getProductAll);
router.get("/products-select", productController.getAllProductSelect);
router.get("/category", categoryController.getAllCategory);
router.get("/users", usercontroller.getAllUser);
router.get("/orders", orderController.getAllOrder);
router.get("/ordersN", orderNController.getAllOrderN);
router.get("/discounts", discountController.getAllDiscount);
router.get("/static", productController.getProductStatic);
router.get("/static-stock", productController.getProductStock);
router.get("/static-bancham", productController.getProductStaticBanCham);
router.get("/orders-count", orderController.countOrder);
router.get("/ordersConfirm-count", orderController.countOrderConfirm);
router.get("/products-count", productController.countProduct);
router.get("/products-count-hsd", productController.countProductHSD);
router.get("/login", usercontroller.authenUser);
router.post("/login", usercontroller.handleLogin);
router.get("/users-count", usercontroller.countUser);
router.get("/collect", productController.collectStatic);
router.get("/image/count", productController.countImage);
router.post("/blog/update", blogController.getBlog);
router.post("/user/update", usercontroller.getUser);
router.post("/discount", discountController.createDiscount);
router.post("/blog", blogController.createBlog);
router.post("/product", productController.createProduct);
router.post("/product/update", productController.getProduct);
router.post("/discount/update", discountController.getDiscount);
router.post("/category", categoryController.uploadProductCategory);
router.post("/blog/image", blogController.uploadImage);
router.post("/supplier", supplierController.uploadSupplier);
router.post("/user/add", usercontroller.createUser);

router.put("/blog/update", blogController.updateBlog);
router.put("/user/update", usercontroller.updateCustomer);
router.put("/discount/update", discountController.updateDiscount);
router.put("/order/update", orderController.updateStatusOrder);
router.put("/product/update", productController.updateProduct);

router.delete("/supplier/delete", supplierController.deleteSupplier);
router.delete("/image/delete", productController.deleteImageProduct);
router.delete("/blog/delete", blogController.deleteBlog);
router.delete("/user/delete", usercontroller.deleteUser);
router.delete("/discount/delete", discountController.deleteDiscount);
router.delete("/category/delete", categoryController.deleteCategory);
router.delete("/product/delete", productController.deleteProduct);
module.exports = router;
